### ISSUE TITLE
Curl commands in Swagger UI are incorrect

### ISSUE THREAD

**Issue by michaelhagedon** [APTrust/registry#25]
When I try to use the Swagger UI to get example curl commands, they yield an error. Example:

```bash
curl -X GET "https://demo.aptrust.org/member-api/v3/member-api/v3/objects?page=1&per_page=20" -H "accept: application/json" -H "X-Pharos-API-User: <redacted>" -H "X-Pharos-API-Key: <redacted>"
```

This yields:
```json
{"error":"Missing authorization check for /member-api/v3/member-api/v3/objects"}
```

When I remove the extraneous `/member-api/v3`, it works. I assume it's related to the [servers section](https://github.com/APTrust/registry/blob/master/member_api_v3.yml#L13) and the [paths section](https://github.com/APTrust/registry/blob/master/member_api_v3.yml#L973) both having that string and concatenating, but I didn't test that and so didn't want to send a PR based on that hunch. :-) 

The Swagger UI also doesn't seem to work, but might be a different issue. I get this error on various endpoints after authentication:

```js
TypeError: NetworkError when attempting to fetch resource.
```

**Comment by diamondap** [comment]
This should be fixed in commit https://github.com/APTrust/registry/commit/30d6d26a37ea113bf53830cf92ae8744f0ef33e8, which we can't deploy until later this week or early next week. Both problems stemmed from incorrect server URLs. The server URLs should not have included the paths (problem 1) and should have used the HTTPS protocol, not HTTP (problem 2).

I'll close this once we deploy the new branch and confirm the fixes work on the live Swagger doc site at https://aptrust.github.io/registry/

**Comment by michaelhagedon** [comment]
I suspected they might be related, glad you could confirm. Thank you!
